apiVersion: v1
kind: ConfigMap
metadata:
  name: vecboost-config
data:
  VECBOOST_HOST: "0.0.0.0"
  VECBOOST_PORT: "8080"
  VECBOOST_MODEL_NAME: "BAAI/bge-m3"
  VECBOOST_DEVICE_TYPE: "cuda"
  VECBOOST_MAX_BATCH_SIZE: "32"
  VECBOOST_MAX_CONCURRENT_REQUESTS: "100"
  VECBOOST_TIMEOUT_MS: "60000"
  VECBOOST_LOG_LEVEL: "info"
